
package tutorial9bclient;

import tutorial9bclient.*;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RealService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/Tutorial9B/RealService?wsdl")
public class RealService_Service
    extends Service
{

    private final static URL REALSERVICE_WSDL_LOCATION;
    private final static WebServiceException REALSERVICE_EXCEPTION;
    private final static QName REALSERVICE_QNAME = new QName("http://server/", "RealService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Tutorial9B/RealService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REALSERVICE_WSDL_LOCATION = url;
        REALSERVICE_EXCEPTION = e;
    }

    public RealService_Service() {
        super(__getWsdlLocation(), REALSERVICE_QNAME);
    }

    public RealService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), REALSERVICE_QNAME, features);
    }

    public RealService_Service(URL wsdlLocation) {
        super(wsdlLocation, REALSERVICE_QNAME);
    }

    public RealService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REALSERVICE_QNAME, features);
    }

    public RealService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RealService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RealService
     */
    @WebEndpoint(name = "RealServicePort")
    public RealService getRealServicePort() {
        return super.getPort(new QName("http://server/", "RealServicePort"), RealService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RealService
     */
    @WebEndpoint(name = "RealServicePort")
    public RealService getRealServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "RealServicePort"), RealService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REALSERVICE_EXCEPTION!= null) {
            throw REALSERVICE_EXCEPTION;
        }
        return REALSERVICE_WSDL_LOCATION;
    }

}
