
package codingexercisetwoclient;

import codingexercisetwoclient.*;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestWebService", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWebService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://server/", className = "codingexercisetwoclient.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://server/", className = "codingexercisetwoclient.HelloResponse")
    @Action(input = "http://server/TestWebService/helloRequest", output = "http://server/TestWebService/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param message
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://server/", className = "codingexercisetwoclient.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://server/", className = "codingexercisetwoclient.SendMessageResponse")
    @Action(input = "http://server/TestWebService/sendMessageRequest", output = "http://server/TestWebService/sendMessageResponse")
    public String sendMessage(
        @WebParam(name = "message", targetNamespace = "")
        String message);

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isConnected", targetNamespace = "http://server/", className = "codingexercisetwoclient.IsConnected")
    @ResponseWrapper(localName = "isConnectedResponse", targetNamespace = "http://server/", className = "codingexercisetwoclient.IsConnectedResponse")
    @Action(input = "http://server/TestWebService/isConnectedRequest", output = "http://server/TestWebService/isConnectedResponse")
    public Boolean isConnected();

    /**
     * 
     * @param parameter
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendId", targetNamespace = "http://server/", className = "codingexercisetwoclient.SendId")
    @ResponseWrapper(localName = "sendIdResponse", targetNamespace = "http://server/", className = "codingexercisetwoclient.SendIdResponse")
    @Action(input = "http://server/TestWebService/sendIdRequest", output = "http://server/TestWebService/sendIdResponse")
    public Integer sendId(
        @WebParam(name = "parameter", targetNamespace = "")
        int parameter);

}
