
package cex2client;

import cex2client.*;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CEX2WebService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/CEX2WebServer/CEX2WebService?wsdl")
public class CEX2WebService_Service
    extends Service
{

    private final static URL CEX2WEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CEX2WEBSERVICE_EXCEPTION;
    private final static QName CEX2WEBSERVICE_QNAME = new QName("http://server/", "CEX2WebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CEX2WebServer/CEX2WebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CEX2WEBSERVICE_WSDL_LOCATION = url;
        CEX2WEBSERVICE_EXCEPTION = e;
    }

    public CEX2WebService_Service() {
        super(__getWsdlLocation(), CEX2WEBSERVICE_QNAME);
    }

    public CEX2WebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CEX2WEBSERVICE_QNAME, features);
    }

    public CEX2WebService_Service(URL wsdlLocation) {
        super(wsdlLocation, CEX2WEBSERVICE_QNAME);
    }

    public CEX2WebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CEX2WEBSERVICE_QNAME, features);
    }

    public CEX2WebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CEX2WebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CEX2WebService
     */
    @WebEndpoint(name = "CEX2WebServicePort")
    public CEX2WebService getCEX2WebServicePort() {
        return super.getPort(new QName("http://server/", "CEX2WebServicePort"), CEX2WebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CEX2WebService
     */
    @WebEndpoint(name = "CEX2WebServicePort")
    public CEX2WebService getCEX2WebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "CEX2WebServicePort"), CEX2WebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CEX2WEBSERVICE_EXCEPTION!= null) {
            throw CEX2WEBSERVICE_EXCEPTION;
        }
        return CEX2WEBSERVICE_WSDL_LOCATION;
    }

}
