
package cex2client;

import cex2client.*;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CEX2WebService", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CEX2WebService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://server/", className = "cex2client.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://server/", className = "cex2client.HelloResponse")
    @Action(input = "http://server/CEX2WebService/helloRequest", output = "http://server/CEX2WebService/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findLongestNameInServer", targetNamespace = "http://server/", className = "cex2client.FindLongestNameInServer")
    @ResponseWrapper(localName = "findLongestNameInServerResponse", targetNamespace = "http://server/", className = "cex2client.FindLongestNameInServerResponse")
    @Action(input = "http://server/CEX2WebService/findLongestNameInServerRequest", output = "http://server/CEX2WebService/findLongestNameInServerResponse")
    public String findLongestNameInServer();

    /**
     * 
     * @param s
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addStudentToServer", targetNamespace = "http://server/", className = "cex2client.AddStudentToServer")
    @ResponseWrapper(localName = "addStudentToServerResponse", targetNamespace = "http://server/", className = "cex2client.AddStudentToServerResponse")
    @Action(input = "http://server/CEX2WebService/addStudentToServerRequest", output = "http://server/CEX2WebService/addStudentToServerResponse")
    public String addStudentToServer(
        @WebParam(name = "s", targetNamespace = "")
        Student s);

    /**
     * 
     * @return
     *     returns cex2client.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findStudentWithHighestGrade", targetNamespace = "http://server/", className = "cex2client.FindStudentWithHighestGrade")
    @ResponseWrapper(localName = "findStudentWithHighestGradeResponse", targetNamespace = "http://server/", className = "cex2client.FindStudentWithHighestGradeResponse")
    @Action(input = "http://server/CEX2WebService/findStudentWithHighestGradeRequest", output = "http://server/CEX2WebService/findStudentWithHighestGradeResponse")
    public Student findStudentWithHighestGrade();

    /**
     * 
     * @param test
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStringLengthWithException", targetNamespace = "http://server/", className = "cex2client.GetStringLengthWithException")
    @ResponseWrapper(localName = "getStringLengthWithExceptionResponse", targetNamespace = "http://server/", className = "cex2client.GetStringLengthWithExceptionResponse")
    @Action(input = "http://server/CEX2WebService/getStringLengthWithExceptionRequest", output = "http://server/CEX2WebService/getStringLengthWithExceptionResponse")
    public Integer getStringLengthWithException(
        @WebParam(name = "test", targetNamespace = "")
        String test);

    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isConnected", targetNamespace = "http://server/", className = "cex2client.IsConnected")
    @ResponseWrapper(localName = "isConnectedResponse", targetNamespace = "http://server/", className = "cex2client.IsConnectedResponse")
    @Action(input = "http://server/CEX2WebService/isConnectedRequest", output = "http://server/CEX2WebService/isConnectedResponse")
    public Integer isConnected();

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNameToServer", targetNamespace = "http://server/", className = "cex2client.AddNameToServer")
    @ResponseWrapper(localName = "addNameToServerResponse", targetNamespace = "http://server/", className = "cex2client.AddNameToServerResponse")
    @Action(input = "http://server/CEX2WebService/addNameToServerRequest", output = "http://server/CEX2WebService/addNameToServerResponse")
    public String addNameToServer(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param test
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStringLength", targetNamespace = "http://server/", className = "cex2client.GetStringLength")
    @ResponseWrapper(localName = "getStringLengthResponse", targetNamespace = "http://server/", className = "cex2client.GetStringLengthResponse")
    @Action(input = "http://server/CEX2WebService/getStringLengthRequest", output = "http://server/CEX2WebService/getStringLengthResponse")
    public Integer getStringLength(
        @WebParam(name = "test", targetNamespace = "")
        String test);

}
