
package mockupprototypeaclient;

import mockupprototypeaclient.*;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MockUpPrototypeService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/MockUpPrototypeAServer/MockUpPrototypeService?wsdl")
public class MockUpPrototypeService_Service
    extends Service
{

    private final static URL MOCKUPPROTOTYPESERVICE_WSDL_LOCATION;
    private final static WebServiceException MOCKUPPROTOTYPESERVICE_EXCEPTION;
    private final static QName MOCKUPPROTOTYPESERVICE_QNAME = new QName("http://server/", "MockUpPrototypeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/MockUpPrototypeAServer/MockUpPrototypeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MOCKUPPROTOTYPESERVICE_WSDL_LOCATION = url;
        MOCKUPPROTOTYPESERVICE_EXCEPTION = e;
    }

    public MockUpPrototypeService_Service() {
        super(__getWsdlLocation(), MOCKUPPROTOTYPESERVICE_QNAME);
    }

    public MockUpPrototypeService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MOCKUPPROTOTYPESERVICE_QNAME, features);
    }

    public MockUpPrototypeService_Service(URL wsdlLocation) {
        super(wsdlLocation, MOCKUPPROTOTYPESERVICE_QNAME);
    }

    public MockUpPrototypeService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MOCKUPPROTOTYPESERVICE_QNAME, features);
    }

    public MockUpPrototypeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MockUpPrototypeService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MockUpPrototypeService
     */
    @WebEndpoint(name = "MockUpPrototypeServicePort")
    public MockUpPrototypeService getMockUpPrototypeServicePort() {
        return super.getPort(new QName("http://server/", "MockUpPrototypeServicePort"), MockUpPrototypeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MockUpPrototypeService
     */
    @WebEndpoint(name = "MockUpPrototypeServicePort")
    public MockUpPrototypeService getMockUpPrototypeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "MockUpPrototypeServicePort"), MockUpPrototypeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MOCKUPPROTOTYPESERVICE_EXCEPTION!= null) {
            throw MOCKUPPROTOTYPESERVICE_EXCEPTION;
        }
        return MOCKUPPROTOTYPESERVICE_WSDL_LOCATION;
    }

}
