
package mockupprototypeaclient;

import mockupprototypeaclient.*;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MockUpPrototypeService", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MockUpPrototypeService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://server/", className = "mockupprototypeaclient.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://server/", className = "mockupprototypeaclient.HelloResponse")
    @Action(input = "http://server/MockUpPrototypeService/helloRequest", output = "http://server/MockUpPrototypeService/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param string1
     * @param string2
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findShortestBetween", targetNamespace = "http://server/", className = "mockupprototypeaclient.FindShortestBetween")
    @ResponseWrapper(localName = "findShortestBetweenResponse", targetNamespace = "http://server/", className = "mockupprototypeaclient.FindShortestBetweenResponse")
    @Action(input = "http://server/MockUpPrototypeService/findShortestBetweenRequest", output = "http://server/MockUpPrototypeService/findShortestBetweenResponse")
    public String findShortestBetween(
        @WebParam(name = "string1", targetNamespace = "")
        String string1,
        @WebParam(name = "string2", targetNamespace = "")
        String string2);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findShortestBetweenWithException", targetNamespace = "http://server/", className = "mockupprototypeaclient.FindShortestBetweenWithException")
    @ResponseWrapper(localName = "findShortestBetweenWithExceptionResponse", targetNamespace = "http://server/", className = "mockupprototypeaclient.FindShortestBetweenWithExceptionResponse")
    @Action(input = "http://server/MockUpPrototypeService/findShortestBetweenWithExceptionRequest", output = "http://server/MockUpPrototypeService/findShortestBetweenWithExceptionResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://server/MockUpPrototypeService/findShortestBetweenWithException/Fault/Exception")
    })
    public String findShortestBetweenWithException(
        @WebParam(name = "a", targetNamespace = "")
        String a,
        @WebParam(name = "b", targetNamespace = "")
        String b)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findShortestAmongAllStrings", targetNamespace = "http://server/", className = "mockupprototypeaclient.FindShortestAmongAllStrings")
    @ResponseWrapper(localName = "findShortestAmongAllStringsResponse", targetNamespace = "http://server/", className = "mockupprototypeaclient.FindShortestAmongAllStringsResponse")
    @Action(input = "http://server/MockUpPrototypeService/findShortestAmongAllStringsRequest", output = "http://server/MockUpPrototypeService/findShortestAmongAllStringsResponse")
    public String findShortestAmongAllStrings();

    /**
     * 
     * @param firstString
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addString", targetNamespace = "http://server/", className = "mockupprototypeaclient.AddString")
    @ResponseWrapper(localName = "addStringResponse", targetNamespace = "http://server/", className = "mockupprototypeaclient.AddStringResponse")
    @Action(input = "http://server/MockUpPrototypeService/addStringRequest", output = "http://server/MockUpPrototypeService/addStringResponse")
    public String addString(
        @WebParam(name = "first_String", targetNamespace = "")
        String firstString);

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isConnected", targetNamespace = "http://server/", className = "mockupprototypeaclient.IsConnected")
    @ResponseWrapper(localName = "isConnectedResponse", targetNamespace = "http://server/", className = "mockupprototypeaclient.IsConnectedResponse")
    @Action(input = "http://server/MockUpPrototypeService/isConnectedRequest", output = "http://server/MockUpPrototypeService/isConnectedResponse")
    public Boolean isConnected();

    /**
     * 
     * @param person
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findShortestBetweenNameAndSurname", targetNamespace = "http://server/", className = "mockupprototypeaclient.FindShortestBetweenNameAndSurname")
    @ResponseWrapper(localName = "findShortestBetweenNameAndSurnameResponse", targetNamespace = "http://server/", className = "mockupprototypeaclient.FindShortestBetweenNameAndSurnameResponse")
    @Action(input = "http://server/MockUpPrototypeService/findShortestBetweenNameAndSurnameRequest", output = "http://server/MockUpPrototypeService/findShortestBetweenNameAndSurnameResponse")
    public String findShortestBetweenNameAndSurname(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

}
